### ISSUE TITLE
Support for soundboard

### ISSUE THREAD

**Issue by manolo754** [oSumAtrIX/nitro-bypass#9]
The new soundboard feature on Discord has a hidden feature that can only be done with Discord nitro.
You could update the plugin by skipping the nitro and let you put the sounds of the servers you have joined, that is the function of the nitro.

**Comment by oSumAtrIX** [comment]
Please explain what you mean, I don't understand you.

**Comment by manolo754** [comment]
> Please explain what you mean, I don't understand you.

Discord has added a new feature to the nitro subscription service that allows you to play sounds from other servers to which you have joined.

**Comment by oSumAtrIX** [comment]
Requires playing the audio through the mic, out of scope
